### ISSUE TITLE
Record subtasks and progress

### ISSUE THREAD

**Issue by gavv** [gavv/tagberry#27]
- [ ] Render checkboxes in markdown
- [ ] Track progress and store in model and db
- [ ] Render progress in record and calendar
